### ISSUE TITLE
White Space and newlines

### ISSUE THREAD

**Issue by twalmsley** [MODLanguage/grammar#10]
not allowed in pairs, so formatting like this is not allowed (but would be easy to add if it would be useful):
```
		a = 
			b =
				c

**Comment by elliottinvent** [comment]
Please see if this is possible without impacting the interpreter or breaking anything in the grammar.

**Comment by twalmsley** [comment]
Another straightforward fix - added unit test to the java interpreter, both will be in the next pull request.
