### ISSUE TITLE
More Compact Conditionals

### ISSUE THREAD

**Issue by twalmsley** [MODLanguage/grammar#11]
```
country=uk
british={country.u=GB|UK?true/?false}
```
Could possibly be reduced to:
```
country=uk
british={country.u=GB|UK?}
```
With a suitable grammar change.

**Comment by elliottinvent** [comment]
I really like this, please take a look at how this could be changed without too much impact on the interpreter.

**Comment by twalmsley** [comment]
This is a straightforward change to the grammar, and all the existing tests still pass, but I only made the change to ``modl_value_conditional`` because it requires an ``else`` clause and this new grammar will always return ``true`` or ``false``. The other conditionals have optional ``else`` clauses so we probably don't want to allow this format in those situations - do you agree @elliottinvent @alexdalitz ? (I won't commit the changes until you've had a chance to reply)

**Comment by elliottinvent** [comment]
Yes I agree, I think this is the only way it can work. Please commit and close.

**Comment by twalmsley** [comment]
Change submitted.

**Comment by elliottinvent** [comment]
This doesn't seem to be working on the new playground which @quentin-num recently put online, @alexdalitz does this work at your end? Not sure if it required an interpreter change?

**Comment by elliottinvent** [comment]
It works on new playground using latest version so this isn't an issue.

**Comment by elliottinvent** [comment]
This works:
```
_country = gb
support_contact = {country=gb?}
```
but this doesn't:
```
_country = gb
support_contact = {
  country=gb?
}
```

**Comment by twalmsley** [comment]
Made a minor change to the grammar to fix this - no interpreter code changes necessary. The interpreters should work fine once their ANTLR4 files are updated. I also added a test case for it.
