### ISSUE TITLE
Optional modl_operator

### ISSUE THREAD

**Issue by twalmsley** [MODLanguage/grammar#12]
The modl_operator in modl_condition is optional so can be excluded while still parsing correctly, but the behaviour is incorrect. E.g.
```
		country=uk
		british={country.u=GB|UK?true/?false}
```
Can be parsed successfully as:
```
		country=uk
		british={country.u GB|UK?true/?false}
```
(by removing the '=' in the condition)
But the results are incorrect because british is set to 'false' in the second case.

**Comment by elliottinvent** [comment]
This is behaving as expected although I agree it's a confusing example.

It's evaluating "country. u GB" as key and because it's not assigned a value, it's false. 

This will return true:
```
_country.u GB = test
british={country.u GB|UK?true/?false}
```

This is because we allow keys to include spaces (as with JSON). A way to demonstrate how this can be used is:
```
_first name = John
_last name = Smith
full name = `%first name` `%last name`
```
