### ISSUE TITLE
modl_value_conditional_return allows colons

### ISSUE THREAD

**Issue by twalmsley** [MODLanguage/grammar#14]
modl_value_conditional_return allows colons, so this is valid:
```	
		b=2;c=2;d=2;e=2;a={{b=c & d=e}?v1:v2:v3/?v4:v5:v6}
```		
I would expect this to return the modl_nb_arrays 'v1:v2:v3' and 'v4:v5:v6', is this correct? (it sets a=2 due to the general issue with expression evaluation)

**Comment by elliottinvent** [comment]
I agree, that should be the output and is in the playground. 

@alexdalitz, perhaps the issues mentioned above with expression evaluation are not an issue in the plaground (because it uses an older version of the interpreter) but are an issue with the new version of the interepreter?

**Comment by alexdalitz** [comment]
Added to test cases
