### ISSUE TITLE
Possibly ambiguous expressions

### ISSUE THREAD

**Issue by twalmsley** [MODLanguage/grammar#16]
Does 'c!=de|at?' mean 'c!=de & c!=at'?
Does 'c!=de&at?' mean the same thing?

**Comment by elliottinvent** [comment]
Yes , these should result in the same:

```
_c = de
result={
  c!=de|at?
    German or Austrian
  /?
    Other
}
```

```
_c = de
result={
  c!=de&c!=at?
    German or Austrian
  /?
    Other
}
```

```
_c = de
result={
  c!=de&at?
    German or Austrian
  /?
    Other
}
```

The playground works this way, I'll update spec.

**Comment by alexdalitz** [comment]
I've also added a test case for this

**Comment by alexdalitz** [comment]
@elliottinvent could you please close this issue once the spec is updated?

**Comment by elliottinvent** [comment]
I don't think there's any need to update the spec since these work as expected - just three different ways to do the same thing. Happy to consider making a spec update but interested in any input on where and how best to do it. For now I'll close but feel free to re-open it.
