### ISSUE TITLE
Double negatives

### ISSUE THREAD

**Issue by twalmsley** [MODLanguage/grammar#17]
Should '!a!=2' be interpreted as 'a=2'?

**Comment by elliottinvent** [comment]
Yes, @alexdalitz please test.

```
_test = 1
result={
  test=1?
    one
  /?
    Other
}
```
Should equal the same as:
```
_test = 1
result={
  !test!=1?
    one
  /?
    Other
}
```

**Comment by twalmsley** [comment]
It works in the playground but I had a problem in the latest java interpreter - Alex please check.

**Comment by alexdalitz** [comment]
Added to tests
