### ISSUE TITLE
Observation

### ISSUE THREAD

**Issue by twalmsley** [MODLanguage/grammar#18]
We can't use () to make precedence clearer like we can in most programming languages. We'll just have to accept this I think.

**Comment by elliottinvent** [comment]
Precedence can be set with `{` and `}`. This is covered in the [spec](https://modl.uk/specification#grouping-test-parts). Please let me know if grammar or interpreter does not include it.

**Comment by twalmsley** [comment]
Yes the curly braces solve the problem, I hadn't spotted that they could be used for this purpose. There is another issue with expression evaluation but that is a separate issue on the java_interpreter repo.
