### ISSUE TITLE
Operator Precedence

### ISSUE THREAD

**Issue by twalmsley** [MODLanguage/grammar#19]
The precedence of '=' is not specified - equality should probably be the same precedence as '!='.
- Except in something like '!a=2' where the '!' is higher precedence than '=', so it means ((!a)=2) when I suspect it should mean !(a=2)

**Comment by elliottinvent** [comment]
@elliottinvent to update Spec
@alexdalitz please update interpreter so that `!a=2` behaves the same as `a!=2`

**Comment by alexdalitz** [comment]
@twalmsley  Are any grammar changes required for this please?

**Comment by alexdalitz** [comment]
does this cover it?

```  {"input": "a=2;b=!a=2",
   "minimised_modl": "a=2;b=!a=2",
   "expected_output": "\"a\":2, \"b\":false"},
```

**Comment by twalmsley** [comment]
@alexdalitz Looks like I failed to mention that this is for conditional expressions. No grammar changes needed - it can parse these with no problems:

```
tony=hungry
needs_food_1={tony=hungry?true/?false}
needs_food_2={!tony=hungry?false/?true}
needs_food_3={tony!=hungry?false/?true}
needs_food_3={!tony!=hungry?true/?false}
```
And the playground gives the expected result:
```
[
    {
        "tony": "hungry"
    },
    {
        "needs_food_1": true
    },
    {
        "needs_food_2": true
    },
    {
        "needs_food_3": true
    },
    {
        "needs_food_3": true
    }
]
```
but the current version of the interpreter gives the wrong result:
```
[ {
  "tony" : "hungry"
}, {
  "needs_food_1" }, {
  "needs_food_2" }, {
  "needs_food_3" }, {
  "needs_food_3" } ]
```

**Comment by alexdalitz** [comment]
OK - the hungry Tony tests now pass :)
