### ISSUE TITLE
Stray tokens files

### ISSUE THREAD

**Issue by twalmsley** [MODLanguage/grammar#20]
In the antlr4 directory there are some `*.tokens` files that don't need to be saved as they're generated by ANTLR4. Also, they seem to interfere with code generation on Windows and result in test failures due to incorrect token constants.

I found this when trying to remove HASH_PREFIX from the `MODLLexer.g4` file - its fine when the code is generated on Mac, but the `*.tokens` files aren't updated properly on Windows resulting in a stray HASH_PREFIX constant that causes the problem.

**Comment by elliottinvent** [comment]
Thanks, please delete and add to .gitignore

**Comment by twalmsley** [comment]
Fixed and submitted a pull request.
