### ISSUE TITLE
Upcase method not invoked

### ISSUE THREAD

**Issue by twalmsley** [MODLanguage/grammar#25]
The input:
```
_testing = quick-test of John's variable_methods
url_encode_example = %testing.ue
```
Produces:
```
{
    "url_encode_example": "quick-test+of+John%27s+variable_methods"
}
```
but should produce:
```
{
    "url_encode_example": "QUICK-TEST+OF+JOHN%27S+VARIABLE_METHODS"
}
```
@alexdalitz please confirm this and I'll update the grammar tests.

**Comment by alexdalitz** [comment]
Could you please explain why you expect the characters to be upcased?

I’m using java.net.URLEncoder to do this, and am not sure why (or how!) it should be expected to upcase?

result = URLEncoder.encode(parameter, StandardCharsets.UTF_8.toString());

Thanks,


Alex.

**Comment by twalmsley** [comment]
The `.ue` extension is a chained sequence of two methods, one for uppercasing the text and one for url-encoding it.

**Comment by alexdalitz** [comment]
Ah I understand now - thanks!

The chained methods should be chained with a `.` so we'd have :

`url_encode_example = %testing.u.e`

**Comment by twalmsley** [comment]
I missed that part of the spec. - I can fix the test case to `%testing.u.e` and change the result to upper case.

What should be the correct result for `%testing.ue`?

**Comment by twalmsley** [comment]
Tests updated by Alex. If there is a `.ue` it should just pass through unchanged since it doesn't match a method (unless of course there is a custom method called `ue`).
