### ISSUE TITLE
Non-UTF-8 Input Characters in tests

### ISSUE THREAD

**Issue by twalmsley** [MODLanguage/grammar#26]
The following base test uses non-UTF-8 characters for the apostrophes so it fails to parse in the Ruby interpreter. The spec says the input files should be valid UTF-8 so this test uses invalid MODL (it works in the playground however!):
```
_colour = green
_test = { colour=green? true /? false }

{
 !test?
   result=it’s not green
 /?
   result=it’s green
}
```
The apostrophe used in this test is `\u2019` when it should be `\u0027`
@elliottinvent do we change the spec and the grammar or stick to the UTF-8 restriction? Personally I prefer the latter.

**Comment by alexdalitz** [comment]
Sorry about this. Yes, the Java interpreter seems quite happy with it. However, I've changed it in the tests now - it will end up in the grammar repo soon. Thanks!

**Comment by alexdalitz** [comment]
@twalmsley Can we close this now please?
