### ISSUE TITLE
Array problem

### ISSUE THREAD

**Issue by elliottinvent** [MODLanguage/grammar#28]
Pretty sure these examples used to work but don't anymore

This is standard stuff:
```
[
one;
two;
three
]
```
This is an example with a trailing comma, this can be useful for config files:
```
[
one;
two;
three;
]
```
Both error:
-> `line 2:4 extraneous input '\n' expecting {NULL, TRUE, FALSE, SC, LBRAC, LSBRAC, NUMBER, STRING, QUOTED, '{'} `

**Comment by alexdalitz** [comment]
That is a grammar-level error, I’m afraid.

**Comment by twalmsley** [comment]
This changed was discussed on the 7th of Feb when I was making the change to allow blank entries in arrays (`[a;;;b]` or `a:::b` etc.) and the conclusion was that trailing semicolons (and colons for NB arrays) would be disallowed. Do we want them back in?

This change also broke the NEWLINEs format, so I need to fix that anyway.

**Comment by elliottinvent** [comment]
Yeah I recall that discussion. Maybe we could allow trailing semi-colons just on multi-line arrays?

What do you think? I could go either way. On one hand I don't like it because the minified version is not consistent with the non-minified version but on the other hand trailing commas are useful in config files.

We need blank array entries more than we need trailing semi-colons so if there's a way to have both great, if not stick with what we've got.

**Comment by twalmsley** [comment]
I'll have a go at putting trailing semicolons back in and see how it goes. It might be possible to remove them in the minified version. (Is there an actual minifier? I don't see a repo for one.)

**Comment by elliottinvent** [comment]
Sorry, to clarify I meant the manually minified version, i.e. no newlines or spaces (not multi-line).

**Comment by twalmsley** [comment]
Added support for trailing ; in arrays and re-instated support for the newline-separated format. Added tests for the formats in the original comment and removed some error tests that are no longer valid.
