### ISSUE TITLE
Standard Error Messages for Failures

### ISSUE THREAD

**Issue by twalmsley** [MODLanguage/grammar#29]
Is it worth standardising error messages? The error_tests.json file could be updated to hold the expected message for each error for all interpreters to conform to.

**Comment by alexdalitz** [comment]
Good idea!

**Comment by elliottinvent** [comment]
Yes, we should definitely standardise error messages.

**Comment by twalmsley** [comment]
Started working on this and I have a working Ruby version. I'll publish it and fix the Java interpreter once I know the Swift interpreter won't be impacted too badly.

**Comment by twalmsley** [comment]
Ruby and Java interpreters now produce the same error messages for the `error-tests.json` tests.
The `error_tests.json` file is now the same format as the `base_tests.json` file so it can be edited using the TestViewer.html utility.

I'll go ahead and release the changes since I was only holding off to prevent Nick having extra work during his final week, but now he's gone it shouldn't be a problem.

**Comment by twalmsley** [comment]
Java v0.0.10 released and published.
Ruby v0.3.15 released and published.
