### ISSUE TITLE
Graves and References Handling

### ISSUE THREAD

**Issue by twalmsley** [MODLanguage/grammar#35]
For discussion:
```
_replace_me=new value;

one=%replace_me.u;

two=`replace_me`.u;

three=`replace_me.u`;

four=`%replace_me.u`;

five=`%replace_me`.u;
```
Should produce:
```
[
    {
        "one": "NEW VALUE"
    },
    {
        "two": "REPLACE_ME"
    },
    {
        "three": "replace_me.u"
    },
    {
        "four": "NEW VALUE"
    },
    {
        "five": "new value.u"
    }
]
```
Because:

1. `one` has a reference that needs to be replaced and converted to upper case.
2. `two` is not a reference so shouldn't be replaced, but _should_ be converted to upper case because we are supposed to run methods on graved strings.
3. `three` is not a reference and has no methods outside the graves so should be de-graved but otherwise unchanged.
4. `four` is a reference and the `.u` is attached to it so it should be replace with `new value` then converted to upper case.
5. `five` is substituted with a new value to produce `new value.u` which is not a reference or a graved string so no further processing takes place.

See the specification Section 12, item 10, for how to handle graved strings.

**Comment by sigmundfridge** [comment]
Also, potentially an obvious one but for clarity
`six=replace_me.u;`
should return
`{six: "replace_me.u"}`
i.e. a string only has methods performed on it if it is within graves

**Comment by sigmundfridge** [comment]
I'm a little unsure about `five`.
My assumption would have been that the interpretation order would be 
1) ``five=`%replace_me`.u;``
2) ``five=`new value`.u;``
3) `{five: "NEW VALUE"}`

whereas the order above is a single step getting the reference and removing the graves

1) ``five=`%replace_me`.u;``
2) ``five=new value.u;``
3) `{five: "new value.u"}`

Whilst I can see the benefits of this (it gives a unique answer rather than just being a more esoteric version of `four`), my initial impression as a user would be that converting an object reference wouldn't necessary remove the graves either side of it but instead imply that the result could be represented as a string.

**Comment by twalmsley** [comment]
Yes `five` is debatable, and its only like this because I'm quoting what the Ruby interpreter does at the moment (which may be wrong of course). Moves are afoot to try to remove any ambiguity so with a bit of luck we'll soon have it resolved.

**Comment by sigmundfridge** [comment]
I'm rewriting the Swift as it currently handles `three` incorrectly and also a potential variety of other cases such as `` `web.com.u` ``. My gut instinct is that my first flow above is easier to implement as it can do all the obj ref in one step to produce an example of `two` , and then at some point in the future do all the `` `string`.method``. However, the second flow is not impossible to implement with the current Swift approach so it just depends on what is the accepted result.

A secondary question is what happens in `one`, `four`, `five` when `_replace_me` isn't a string

**Comment by twalmsley** [comment]
Elliott is updating the spec so hopefully that will resolve most if not all of the problems above.

If `_replace_me` isn't a string then it depends - other primitive types should probably raise an error, as should arrays, but if the result is a map then we should look for a key of `u` and use that as the result or raise an error if there isn't one. `five` should be resolved by the new spec.

**Comment by twalmsley** [comment]
Added a suggested set of results to the `base_tests.json` file for Elliott to review.

**Comment by twalmsley** [comment]
Resolved by the new grammar and base_tests.
