### ISSUE TITLE
Grammar problem - escaped grave

### ISSUE THREAD

**Issue by twalmsley** [MODLanguage/grammar#36]
Given:
```
a= %`x`.p;
b= %~`x`.p;
c= %`x`.p;
```
The ANTLR4 parser reports an error on line 3 due to the escaped grave on line 2 - removing the escape allows it to be parsed successfully.

@elliottinvent would you expect this to work or can we just let it fail as an invalid reference?

**Comment by twalmsley** [comment]
This also fails to parse but should probably be accepted:
```
a=~`x~`.p;
a=`x`.text;

```

**Comment by twalmsley** [comment]
We should probably ignore this problem since we can use this instead:
```
a="~`x~`.p";
```

**Comment by elliottinvent** [comment]
```
b= %~`x`.p;
```
Should fail because there isn't two matching graves or quotes (since the first grave above is escaped).

**Comment by elliottinvent** [comment]
Both of these parse for me separately:
```
a=~`x~`.p;
a=`x`.text;
```
But not together, looking at the grammar to see why.

**Comment by twalmsley** [comment]
I tried some grammar changes to get the above to parse together but didn't find any obvious quick fixes. The tilde isn't allowed in GRAVED strings but allowing it didn't get me any further. 

The first tilde is causing the problem, and it parses if that is removed, but the result looks like it _should_ be rejected.

It might be best at this stage not to make any grammar changes if there's a workaround like the quoted version above.

**Comment by elliottinvent** [comment]
Have got this working with small grammar tweak:

```
a=~`x~`.p;
a=`x`.text;
```

Have added it as a new branch to experiment with.

**Comment by twalmsley** [comment]
Escaped graves are invalid syntax, although the parser accepts them inside quoted strings.
