### ISSUE TITLE
Grammar Problem - double quotes

### ISSUE THREAD

**Issue by twalmsley** [MODLanguage/grammar#37]
this fails to parse:
```
a="x".p;
```
but its fine if the `.p` is removed, or if we use graves instead of double quotes, or if both double quotes are escaped.

Is this a problem that needs to be fixed or can we live with it?

**Comment by twalmsley** [comment]
This can probably be ignored since it can be written as:
```
a="x.p";
```
 I've looked into making graves and quotes behave the same way before and failed to get a working grammar - I expect it would mean a major restructure  and we should just accept that graves will never be the same as quotes.

**Comment by elliottinvent** [comment]
I've got a new version of the grammar that deals with `a="x".p;` ok and hasn't had any trouble with a bunch of random tests I've given it. Have added as branch `elliott-grammar-changes`.

**Comment by twalmsley** [comment]
This doesn't parse with the new grammar, but if that is now correct behaviour the ticket can be closed.

**Comment by elliottinvent** [comment]
Yes this should fail.
