### ISSUE TITLE
Lexer Grammar Observations

### ISSUE THREAD

**Issue by twalmsley** [MODLanguage/grammar#4]
- HASH_PREFIX is absorbed into STRING and is not recognised as a separate token. It isn't mentioned in the specification and isn't handled by the java interpreter.

- STRING and CSTRING are greedy which prevents detection of tokens such as INSIDE_GRAVES and as alread mentioned, HASH_PREFIX. These cases need to be handled by custom code in the Interpreter/ModlParsed classes.

- HASH_PREFIX and GRAVED are still required otherwise the unit tests fail.

Is there a separate mechanism to disallow characters that are invalid for DNS TXT records? (Since MODL supports characters that DNS can't handle.)

**Comment by elliottinvent** [comment]
`HASH_PREFIX` required for:

```
trending=#foo
```

We've now added some tests to show why HASH_PREFIX is required.
