### ISSUE TITLE
Newlines before semicolons

### ISSUE THREAD

**Issue by twalmsley** [MODLanguage/grammar#5]
```
A structure cannot have a semicolon on the next line, e.g.

		a=1:2:3;
		b=4:5:6

	is valid, but
		
		a=1:2:3
		;
		b=4:5:6

	is not.

**Comment by elliottinvent** [comment]
If this is simple enough to add in then happy to add it in to allow flexible formatting

**Comment by twalmsley** [comment]
This was a straightforward fix - I added some tests to the java interpreter as well, and both will be in upcoming pull requests.
