### ISSUE TITLE
Mixed arrays and nb_arrays

### ISSUE THREAD

**Issue by twalmsley** [MODLanguage/grammar#6]
```
This is a valid array:

	x=[1;;;;;;;2:::::::::3;;;;;;;;;;4:::::::::5]

**Comment by elliottinvent** [comment]
Yes, it should be a valid (if a bit bizzare) and is the same as #7

**Comment by twalmsley** [comment]
The example above produces a parse tree that implies the result should look like this:
```
x=[1;;;;;;;[2;;;;;;;;;3];;;;;;;;;;[4;;;;;;;;;5]]
```
but the java interpreter produces:
```
{
  "x" : [ 1, null, null, null, null, null, null, 2, null, null, null, null, null, null, null, null, 3, null, null, null, null, null, null, null, null, null, 4, null, null, null, null, null, null, null, null, 5 ]
}
```
(a flat array similar to issue#7) 
(can't test in the playground since it can't handle empty array values)
@elliottinvent please reassign to @alexdalitz

**Comment by alexdalitz** [comment]
I've added this to the tests, so I'm going to close this issue in the grammar (as it becomes an issue for the interpreters to get the tests working).
