### ISSUE TITLE
Nested Arrays

### ISSUE THREAD

**Issue by twalmsley** [MODLanguage/grammar#7]
Given:

```
x=[1;2:3:4]
```

The grammar says this is an array with 2 entries, the first is the number 2 and the second is the NB array 2:3:4, but the interpreter returns it as the 4-element array [1;2;3;4]. The ANTLR4 rule test parses it correctly.

I would expect to refer to the number 3 as %x>1>1, but I have to use %x>2 instead.

It might be worth disallowing modl_nb_array as a member of modl_array to force 'proper' nesting of arrays. (I tried it and all of the current unit tests still pass.)

**Comment by elliottinvent** [comment]
I agree with you here and your expectation.

This doesn't work in the playground at the moment, if the parse tree in the grammar is correct then this will be an interpreter issue for @alexdalitz to take a look at.

**Comment by twalmsley** [comment]
The playground produces an error when parsing ``x=[1;2:3:4]`` :
```
line 1:6 extraneous input ':' expecting {NULL, TRUE, FALSE, NEWLINE, SC, LBRAC, LSBRAC, RSBRAC, NUMBER, STRING, QUOTED, '{'}
```
While the Java interpreter produces this, which is incorrect:
```
{
  "x" : [ 1, 2, 3, 4 ]
}
```
The parse tree interprets the input correctly as a 2-element array of '1' and an nb_array of 2:3:4, so the result should be something like:
```
{
  "x" : [ 1, [2;3;4] ]
}
```
See issue#7 for more information about mixed arrays and nb_arrays. (@elliottinvent please reassign to @alexdalitz )

**Comment by alexdalitz** [comment]
Added this to tests :
`  {"input": "x=[1;2:3:4]\na=%x>1>1",
   "minimised_modl": "x=[1;2:3:4]\na=%x>1>1",
   "expected_output": "{\"x\": [1,[2,3,4]], \"a\":3}"},
`
